[project]
name = "cardgame"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jinja2>=3.1.6",
]

[project.scripts]
cardgame = "cardgame:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
